# Use root/mysql as user/password credentials

version: '3.8'

services:
  springboot-app:
    image: springboot-app
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_PORT: 3306
  db:
    container_name: mysqldb
    image: mysql
    command:
      --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: restapi_example
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"