spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restapi_example?serverTimezone=UTC
    username: root
    password: 233258OA
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
